\frontmatter

# 前言 {- #frontmatter}

本文内容均来自个人对相关材料的理解，事实上，直到这本书的内容定型时，我的代码水平还处在初级水平，因此，如果你刚接触 R，不要把这本书当作规范，因为成型后我几乎没怎么改过，一是懒，二是忙。文中内容**并未经过权威认证，如有异议，请参考 R 软件及相关软件包的使用手册或相关模型的文献**。本文所使用代码均只做示例代码使用，在做实际分析时，请结合自己的实验数据及模型使用条件做相应的调整。本文内容仅针对
LI-6800 与 LI-6400XT 光合仪数据，尤其是 RACiR\texttrademark 部分，仅针对 LI-6800
进行分析，且目前市面上仅 LI-6800 光合仪可完成此项数据的测量。如您有 LI-6400XT 或 LI-6800 使用操作相关方面的问题请发送至：

[zhujiedong@ecotek.com.cn](zhujiedong@ecotek.com.cn)

如有与本文数据分析相关的内容请发送至我个人邮箱（本文是业余爱好，内容虽与公司仪器相关，但并不是我领薪水的工作内容）：

[zhujiedong@yeah.net](zhujiedong@yeah.net)

以便我们对相关内容做出修正。

当然，如果您有 github 帐号，优先欢迎在 github 提交：

[github地址](https://github.com/zhujiedong/photoanalysis)

gitee 也有同步版本

[gitee 地址](http://zhu_jie_dong.gitee.io/photoanalysis/)

如有其他仪器问题或者仪器购买需求，请使用下面方式与我们联系：

* 北京力高泰科技有限公司 

* 网址：[http://www.ecotek.com.cn](http://www.ecotek.com.cn)

* 电话：010-64093960/66001653

* 电子邮件：[info@ecotek.com.cn](info@ecotek.com.cn)

* 地址：北京市西城区西直门南大街2号成铭大厦A座22F


# 版权 {- #copyright}

**本文旨在对广大 LI-6400XT 和 LI-6800 光合仪的用户提供一个数据分析的参考，本人或所在公司并未从中获取任何利益，内容错误疏漏之处，欢迎指正。本人保留一切权利，禁止一切将本文内容用于商业用途的行为，禁止商业公司使用。**


**文中内容如对您有帮助，我很欣慰。但本人水平有限，错误与疏漏之处还请谅解，欢迎讨论，欢迎提出宝贵意见及建议。本人或单位其他售后人员仅有提供相关仪器操作或故障解决的义务，处理数据和分析数据并非我们的本职工作，如有相关需还请多参考本文内容或网上相关资料，不足之处还请谅解。**

\cleardoublepage
